version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ]7YD8£73vIo(
      POSTGRES_DB: cards  # Главная база данных
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cards"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "0.0.0.0:5433:5432"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app:rw
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: sh -c "chown -R node:node /app/node_modules && npm run dev"

  web:
    build: ./backend
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - card_images:/app/card_imgs
    depends_on:
      db:
        condition: service_healthy
    environment:      
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:]7YD8£73vIo(@db:5432/cards
      BOT_TOKEN_HASH: 7505659847:AAF3AoBU0HFInjsPPOqz4KaPmX3M15l9f1U
      FLASK_APP: wsgi:app
    command: >
      sh -c "flask --app wsgi db migrate -m 'Initial migration' &&
      flask --app wsgi db upgrade &&
      gunicorn --bind 0.0.0.0:8000 wsgi:app"

volumes:
  postgres_data: {}
  frontend_node_modules: {}
  card_images: {}
