"""empty message

Revision ID: 502cf0b8d8bd
Revises: b8468fc8ef2b
Create Date: 2025-03-31 23:10:36.959128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502cf0b8d8bd'
down_revision = 'b8468fc8ef2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_token', schema=None) as batch_op:
        batch_op.drop_column('username')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
